Repository mattermost/mattermost-cloud-database-factory, pull requests merged in 2021-06, with the labels that each got.

#22 [MM-36118] Add functionality in Database Factory to create RDS multitenant db clusters for dbproxy usage.
  api/api.go
  api/api_test.go
  cmd/dbfactory/cluster.go
  internal/tools/terraform/plan.go
  model/cluster.go
  model/cluster_request.go
  terraform/aws/database-factory-postgresql/main.tf
  terraform/aws/database-factory-postgresql/variables.tf
  terraform/aws/modules/rds-aurora-postgresql/main.tf
  terraform/aws/modules/rds-aurora-postgresql/variables.tf
Labels: 2: Infra Review, kind/feature, release-note

#23 Add a cost allocation tag to postgres instances
  .gitignore
  terraform/aws/modules/rds-aurora-postgresql/main.tf
Labels: kind/bug, release-note

#24 Automate release cut, release-notes
  .circleci/config.yml
  .github/workflows/notify-release.yml
  Makefile
  scripts/notify.sh
  scripts/release.sh
Labels: kind/chore, release-note

#25 Upgrade terraform version to 0.14.5
  Makefile
  README.md
  terraform/aws/database-factory-postgresql/main.tf
  terraform/aws/database-factory/main.tf
Labels: kind/feature, release-note

#26 Update golang on circle
  .circleci/config.yml
  go.mod
  go.sum
Labels: kind/chore, release-note

#27 Fix release script
  scripts/release.sh
Labels: kind/bug, release-note

#28 Expose instance type
  cmd/dbfactory/cluster.go
Labels: 2: Dev Review, 2: Infra Review, kind/feature, release-note
