Repository mattermost/mattermost-cloud-database-factory, pull requests merged in 2021-04, with the labels that each got.

#16 Update the configuration in db factory for the maintenance window
  terraform/aws/database-factory-postgresql/variables.tf
  terraform/aws/database-factory/variables.tf
Labels: kind/feature, release-note

#17 Update readme with the latest changes of DB factory
  README.md
Labels: 3: Reviews Complete, kind/documentation, release-note

#19 Bump version for postgresql from 11.8 to 11.9
  terraform/aws/database-factory-postgresql/variables.tf
Labels: 3: Reviews Complete, release-note

#20 Fix format of preference maintenance window
  terraform/aws/database-factory/variables.tf
Labels: 2: Infra Review, kind/bug, release-note

#21 Update terraform version in README
  README.md
Labels: kind/documentation, release-note

#18 Add an extra command to search DB clusters by given tags
  .circleci/config.yml
  Makefile
  README.md
  cmd/dbfactory/cluster.go
  cmd/dbfactory/cluster_test.go
  cmd/dbfactory/mocks.go
  go.mod
  go.sum
Labels: 2: Infra Review, kind/feature, release-note
