Repository mattermost/mattermost-cloud-database-factory, pull requests merged in 2022-08, with the labels that each got.

#39 Add snapshot ARN as an option when creating an RDS instance
  api/api.go
  cmd/dbfactory/cluster.go
  go.mod
  go.sum
  internal/tools/terraform/plan.go
  model/cluster.go
  model/cluster_request.go
  terraform/aws/database-factory-postgresql/main.tf
  terraform/aws/database-factory-postgresql/variables.tf
  terraform/aws/database-factory/main.tf
  terraform/aws/database-factory/variables.tf
  terraform/aws/modules/rds-aurora-postgresql/main.tf
  terraform/aws/modules/rds-aurora-postgresql/variables.tf
  terraform/aws/modules/rds-aurora/main.tf
  terraform/aws/modules/rds-aurora/variables.tf
Labels: release-note, kind/feature

#40 Upgrade circleCI go image to 1.18
  .circleci/config.yml
Labels: release-note, kind/chore

#41 Remove duplicate creation_snapshot_arn
  terraform/aws/database-factory-postgresql/main.tf
Labels: release-note, kind/bug

#38 Fix release automation by updating go to 1.18
  .circleci/config.yml
  go.mod
  go.sum
Labels: release-note, kind/bug
